@startuml
title Inturrupt State
autonumber
participant controller             as ct
participant "controller.IRQLatch"  as ir
participant "program counter"      as pc
participant "Exception PC"         as epc
participant databus                as db
participant dataline               as dl
participant addrline               as ad
participant mem                    as me

group 탐색
  ct --> ir : 인터럽트 존재여부 확인
  note right: 모든 인터럽트 sr래치의 Q를 or해 확인
end

alt 인터럽트 미존재
  ct -> ct : 인터럽트 상태 종료하고 다음명령어 실행 이어서 진행
else 인터럽트 존재
  ct --> ir : 인터럽트 존재하는지 우선순위대로 하나씩 탕색
  alt 해당 인터럽트 미발생
    ct --> ct: 다음 인터럽트 탐색
  else 해당 인터럽트 발생
    ct -> ad : 해당 인터럽트 핸들러 주소 (0x0000 - 0x0047) 상위바이트 접근
    ad --> me
    me --> dl
    dl -> db : 인터럽트핸들러 상위바이트
    db -> pc : 임시레지스터에 상위바이트 적재
    ct -> ad : 해당 인터럽트 핸들러 주소 (0x0000 - 0x0047) 하위바이트 접근
    ad --> me
    me --> dl
    dl -> db : 인터럽트핸들러 하위바이트
    db -> pc : 임시레지스터에 하위바이트 적재
    pc -> epc : 현재 실행할 명령어 주소(반환주소) 적재
    ct --> pc : 임시레지스터에 저장된 주소로 점프
    ct -> ct : 핸들러 실행
    group MRET 실행
      epc -> pc : 반환 주소로 점프
      ct -> ct : 인터럽트 상태 종료하고 다음 명령어 실행 이어서 진행
    end
  end
end

@enduml
